name = "argfolio"
compatibility_date = "2026-02-09"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "argfolio-prod"
database_id = "59879068-6125-4ef4-88fd-a044d754ed5c"
migrations_dir = "migrations"
